version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: lewis254
      MYSQL_DATABASE: auth_system
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    build: .
    container_name: php-app
    volumes:
      - ./project:/var/www/html  
    ports:
      - "8080:80"  
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
