version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: lewis254
      MYSQL_DATABASE: auth_system
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization script
    ports:
      - "3306:3306"
    networks:
      - app-network

  # PHP + Apache (using custom Dockerfile)
  web:
    build: .  # Build the Dockerfile in the current directory
    container_name: php-app
    volumes:
      - ./project:/var/www/html  # Sync local project files with the container
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    depends_on:
      - mysql
    networks:
      - app-network

# Volumes and Networks
volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
